### ISSUE TITLE
Hi, I am trying to use this api but I am getting following errors. Here is my code : 

### ISSUE THREAD

**Issue by newbie-noob** [bytebang/coinpaymentsnet-java-api#1]
**PayUsingCoins.java :**
public class PayUsingCoins extends AppCompatActivity {

    TextView textView;
    Button button;

    String publicKey = "";
    String privateKey = "";

    CoinWorking test = new CoinWorking();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pay_using_coins);

        textView = findViewById(R.id.temp);
        button = findViewById(R.id.aInfo);

    button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                List<String> textD = test.getSupportedCoins();
                String toPut = textD.get(0);
                textView.setText(toPut);
            }
        });
    }
}

**CoinWorking.java**
public class CoinWorking {
    private String privateKey = "";
    private String publicKey = "";

    public List<String> getSupportedCoins() {
        CoinPaymentsAPI api = new CoinPaymentsAPI(publicKey, privateKey);
        List<String> supportedCoins = new ArrayList<>();
        JsonObject j;
        try{
            j = api.set("accepted",1).call("rates");
        } catch(Exception e){
            supportedCoins.add(e.getMessage());
            return supportedCoins;
        }

        for(Map.Entry<String, JsonElement> e : j.entrySet()) {
            JsonObject coin = e.getValue().getAsJsonObject();
            supportedCoins.add(coin.get("name").getAsString());
        }
        return supportedCoins;
    }
}

**activity_pay_using_coins.xml**

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".PayUsingCoins">

    <Button
        android:id="@+id/aInfo"
        android:layout_width="236dp"
        android:layout_height="83dp"
        android:layout_marginStart="108dp"
        android:layout_marginTop="77dp"
        android:layout_marginEnd="67dp"
        android:layout_marginBottom="571dp"
        android:text="Button"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="1.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.0" />

    <TextView
        android:id="@+id/temp"
        android:layout_width="392dp"
        android:layout_height="491dp"
        android:layout_marginStart="10dp"
        android:layout_marginEnd="9dp"
        android:hint="Text will be displayed here"
        android:textSize="20sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/aInfo" />
    
</androidx.constraintlayout.widget.ConstraintLayout>

**Error :** 

2020-01-25 18:09:06.614 1897-1897/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/system/app/Chrome/lib/x86, /system/app/Chrome/Chrome.apk!/lib/x86, /system/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
        at android.app.LoadedApk.updateApplicationInfo(LoadedApk.java:338)
        at android.app.ActivityThread.handleDispatchPackageBroadcast(ActivityThread.java:5388)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1733)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at com.android.server.SystemServer.run(SystemServer.java:454)
        at com.android.server.SystemServer.main(SystemServer.java:294)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)

**Comment by bytebang** [comment]
I have never tested it with android. But the stacktrace indicates that some class can not be found (`Didn't find class "androidx.core.app.CoreComponentFactory"`)

Also be sure to load the dependencies as shown in [ivy.xml](https://github.com/bytebang/coinpaymentsnet-java-api/blob/master/ivy.xml)

**Comment by newbie-noob** [comment]
Hi After adding ivy dependencies I am able to run the app but still I am not able to call api.
Code : 
public JsonObject call(String cmd)
    {

        // Copy the current map to
        Map<String, String> req = new HashMap<>();
        req.putAll(params);
        params.clear();

        // Set the API command and required fields
        req.put("version", "1.2");
        req.put("cmd", cmd);
        req.put("key", this.public_key);
        req.put("format", "json");

        try {
            // Generate the query string
            String post_data = urlEncodeUTF8(req);

            // Calculate the HMAC
            String hmac = new HmacUtils(HmacAlgorithms.HMAC_SHA_512,this.private_key).hmacHex(post_data);
            URL obj = new URL("https://www.coinpayments.net/api.php");
            HttpsURLConnection con = (HttpsURLConnection) obj.openConnection();
            Log.d("Info : ","Connection has been opened");
            //Log.d("Info",hmac);

            // Set the request headers
            con.setRequestMethod("POST");
            con.setRequestProperty("User-Agent", "Chrome/79.0.3945.130");
            con.setRequestProperty("Accept-Language", "en-US,en;q=0.5");
            con.setRequestProperty("HMAC", hmac);

            // Send post request
            con.setDoOutput(true);
            Log.d("Info : ","setDoOutput is working fine");
            DataOutputStream wr;
            try {
                wr = new DataOutputStream(con.getOutputStream());
                wr.writeBytes(post_data);
                wr.flush();
                wr.close();
            } catch(UnknownServiceException use){
                Log.d("Info : ","UnknownServiceException");
            }
            catch(IOException io){
                Log.d("Info : ","IO Exception has occured");
            }
            finally {

                Log.d("Info : ", "Can't get output stream");
                int responseCode = con.getResponseCode();
                Log.d("info : ",Integer.toString(responseCode));
            }
            Log.d("Info : ","request has been sent");
            // Wait for the resüonse code

            //Log.d("Info" ,"Sending 'POST' request to URL : https://www.coinpayments.net/api.php");
           // logger.debug("Post parameters : " + post_data);
           // logger.debug("Response Code : " + responseCode);


            // Read the full response
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            // Parse the JSON response with GSON
            JsonParser jsonParser = new JsonParser();
            JsonElement jsonTree = jsonParser.parse(response.toString());
            JsonObject jsonObject = jsonTree.getAsJsonObject();

            // If there is an error - throw an Exception
            if (jsonObject.get("error").getAsString().equals("ok") == false) {
                Log.d("Info : ","Call error");
                throw new IllegalStateException(jsonObject.get("error").getAsString());
            }

            // Otherwise return the result object
            Gson gson = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
            String prettyJson = gson.toJson(jsonObject);
          //  logger.debug(prettyJson);
            Log.d("Info : ","Call ok ");

            return jsonObject.getAsJsonObject("result");
        }
        catch (Exception e) {
            Log.d("Info : ","Can't make call to api");
         //   logger.error("Exception occured: " + e.getMessage());
            throw new CoinpaymentsApiCallException(e.getMessage());
            //return jsonObject.getAsJsonObject("result");
        }
}

Output I am getting : 
D/Info :: Connection has been opened
    setDoOutput is working fine
D/Info :: Can't get output stream
    Can't make call to api

**Comment by bytebang** [comment]
Are you able to run the Junit tests in the test folder ?

**Comment by newbie-noob** [comment]
Thanks, Its working now :)
I was getting errors because algorithm you have used for hmac generation is deprecated in newer android api and android don't allow networking task on main thread, It worked after I created background threads.
